/* Innovation Research Field Guide — the "plays" catalog.
   De-branded from a private research-program strategy doc. Each play is a research
   project pattern grouped by contribution type. Rendered client-side by field-guide.html.

   Shape: { id, type, title, method, output, cost, impact }
   type ∈ empirical | artifact | methodological | theoretical | dataset | survey | opinion
   cost ∈ "$" (minimal) | "$$" (moderate) | "$$$" (heavier) */
window.PLAYS = [
  /* ---------- 1. Empirical — systematically gathered data for new insight ---------- */
  { id: "emp-diaries", type: "empirical", title: "Lived-Experience Diaries",
    method: "Recruit a small cohort; two weeks of daily energy diaries (paper or app), then semi-structured interviews.",
    output: "Qualitative dataset + lived-experience report", cost: "$",
    impact: "Surfaces real-time burden behind average statistics." },
  { id: "emp-ethno", type: "empirical", title: "Future Scenarios Ethnography",
    method: "Observe community workshops where participants envision their neighborhood decades out.",
    output: "Ethnographic narrative + short documentary cut", cost: "$$",
    impact: "Captures how groups imagine futures — and who is left out." },
  { id: "emp-microclimate", type: "empirical", title: "Micro-Climate Use Diaries",
    method: "Pair low-cost temperature sensors with participant diaries; compare felt comfort to measured data.",
    output: "Comfort-vs-actual dataset", cost: "$",
    impact: "Empirical evidence of insecurity hidden in averages." },
  { id: "emp-field", type: "empirical", title: "Solutions-in-Action Field Studies",
    method: "Document existing grassroots initiatives with interviews and field notes.",
    output: "Case-study series", cost: "$",
    impact: "Elevates under-recognized community-led practice." },
  { id: "emp-longitudinal", type: "empirical", title: "Longitudinal Adoption Panel",
    method: "Deploy a short recurring survey (every 6 months) in target communities.",
    output: "Dynamic panel dataset", cost: "$",
    impact: "Maps how attitudes and barriers shift over time." },
  { id: "emp-heatmap", type: "empirical", title: "Regional Burden Heatmap",
    method: "Join census, utility-rate, and housing data into a spatial cost-to-income map.",
    output: "Interactive heatmap", cost: "$",
    impact: "Pinpoints highest-need areas for program targeting." },
  { id: "emp-timeseries", type: "empirical", title: "Consumption Time-Series",
    method: "Analyze smart-meter data for peak hours and residential inefficiencies.",
    output: "Peak-usage model", cost: "$$",
    impact: "Grounds demand-response program design." },
  { id: "emp-predict", type: "empirical", title: "Cost-Savings Predictive Model",
    method: "Train ML models to estimate savings from efficiency interventions.",
    output: "Savings predictor", cost: "$$",
    impact: "Data-backed estimates raise proposal win rates." },
  { id: "emp-weather", type: "empirical", title: "Efficiency × Weather Study",
    method: "Correlate historical weather with usage across housing types.",
    output: "Correlation report", cost: "$",
    impact: "Optimizes weatherization program design." },

  /* ---------- 2. Artifact — new systems, tools, or prototypes ---------- */
  { id: "art-literacy", type: "artifact", title: "Energy Literacy Toolkit",
    method: "Design a low-tech kit — printable guides, interactive PDFs, or a card deck.",
    output: "Distributable toolkit", cost: "$",
    impact: "Tests how design artifacts build literacy and agency." },
  { id: "art-game", type: "artifact", title: "Futures Decision Card Game",
    method: "Design a role-play game where players navigate equity tradeoffs as policymakers and residents.",
    output: "Playable card game", cost: "$",
    impact: "Engages broad audiences in complex justice issues." },
  { id: "art-2050", type: "artifact", title: "“Artifacts from 2050” Prototypes",
    method: "Build speculative mock devices, posters, and packaging from utopian and dystopian futures.",
    output: "Speculative prototype set", cost: "$",
    impact: "Makes abstract futures tangible and debatable." },
  { id: "art-platform", type: "artifact", title: "Community Platform Mockup",
    method: "Prototype a clickable app for community-run energy management in Figma.",
    output: "Interactive prototype", cost: "$",
    impact: "Demonstrates inclusive, community-centered tech." },
  { id: "art-storymap", type: "artifact", title: "Justice Story Maps",
    method: "Combine personal stories with burden and infrastructure data using GIS story-mapping.",
    output: "Interactive map", cost: "$",
    impact: "Blends qualitative and quantitative views geographically." },
  { id: "art-calc", type: "artifact", title: "Savings Calculator Web Tool",
    method: "Build an interactive dashboard: users enter home details, get estimated savings.",
    output: "Public web calculator", cost: "$$",
    impact: "Generates leads while proving technical depth." },
  { id: "art-alerts", type: "artifact", title: "Smart Usage Alerts Prototype",
    method: "Prototype an app that predicts likely overuse and texts cost-saving tips.",
    output: "Working prototype", cost: "$$",
    impact: "Showcases demand-side management to partners." },
  { id: "art-municipal", type: "artifact", title: "Municipal Resilience Dashboard",
    method: "Aggregate burden, outage, and efficiency metrics across cities.",
    output: "Metrics dashboard", cost: "$$",
    impact: "Positions the practice as a municipal planning partner." },
  { id: "art-riskapi", type: "artifact", title: "Home Energy Risk Score API",
    method: "Design an API that scores homes on cost-risk factors (age, climate zone, etc.).",
    output: "Scoring API", cost: "$$",
    impact: "Helps utilities prioritize households for programs." },

  /* ---------- 3. Methodological — new or improved ways to do research ---------- */
  { id: "met-mapping", type: "methodological", title: "Participatory Mapping Workshops",
    method: "Pop-up sessions with large printed maps; participants mark gaps; add storytelling.",
    output: "Repeatable method + spatial data", cost: "$",
    impact: "Low-cost participatory spatial-data collection." },
  { id: "met-codesign", type: "methodological", title: "Futures Co-Design Workshops",
    method: "Repeatable workshop where participants co-create scenarios with design-fiction artifacts.",
    output: "Documented workshop method", cost: "$",
    impact: "Introduces participatory foresight to the field." },
  { id: "met-backcast", type: "methodological", title: "Equity Backcasting Framework",
    method: "Adapt backcasting — start from a desired future, work backward — and pilot it.",
    output: "Tested method", cost: "$",
    impact: "Structures community future-planning." },
  { id: "met-slr", type: "methodological", title: "Systematic Review Protocol",
    method: "Design and publish a rigorous protocol for literature reviews in the domain.",
    output: "Published protocol", cost: "$",
    impact: "Adds academic rigor; high-citation potential." },
  { id: "met-visual", type: "methodological", title: "Participatory Visual Methods Kit",
    method: "Toolkit for PhotoVoice-style participant photography and video.",
    output: "Method toolkit", cost: "$",
    impact: "Lets communities author their own evidence." },
  { id: "met-index", type: "methodological", title: "Burden Index Algorithm",
    method: "Build a weighted index from income, expenditure, housing, and exposure.",
    output: "Reusable metric", cost: "$",
    impact: "A proprietary metric that signals targeting expertise." },
  { id: "met-cluster", type: "methodological", title: "At-Risk Household Clustering",
    method: "Segment households with K-means / DBSCAN on usage and payment patterns.",
    output: "Segmentation model", cost: "$$",
    impact: "Enables precision program targeting." },
  { id: "met-causal", type: "methodological", title: "Causal Impact Assessment",
    method: "Apply difference-in-differences and propensity matching to past programs.",
    output: "Impact-evaluation method", cost: "$$",
    impact: "Proves program effect — critical for renewals." },
  { id: "met-scenario", type: "methodological", title: "Scenario Modeling Framework",
    method: "Simulate how policies change costs over time under varied economics.",
    output: "Scenario models", cost: "$$",
    impact: "Policy insight without political sensitivity." },

  /* ---------- 4. Theoretical — new models, frameworks, concepts ---------- */
  { id: "the-agencygap", type: "theoretical", title: "The “Agency Gap” Model",
    method: "Synthesize literature, policy analysis, and small focus groups into a conceptual model.",
    output: "Conceptual framework", cost: "$",
    impact: "A new lens on how policy and lived reality diverge." },
  { id: "the-justiceweb", type: "theoretical", title: "The “Justice Web” Model",
    method: "Map feedback loops among access, mobility, health, and environment.",
    output: "Systems framework", cost: "$",
    impact: "Holistic lens beyond siloed issues." },
  { id: "the-specfutures", type: "theoretical", title: "Speculative Futures Framework",
    method: "Combine speculative design and justice theory to analyze how imaginaries shape policy.",
    output: "Theoretical framework", cost: "$",
    impact: "Bridges futures thinking with domain scholarship." },
  { id: "the-invisible", type: "theoretical", title: "The “Invisible Burden” Concept",
    method: "Introduce a construct for hidden costs — bill-uncertainty stress, opportunity cost.",
    output: "New construct", cost: "$",
    impact: "Expands how poverty and burden are measured." },
  { id: "the-postcolonial", type: "theoretical", title: "Critical-History Lens",
    method: "Apply post-colonial theory to transitions in historically marginalized communities.",
    output: "Critical framework", cost: "$",
    impact: "Shows how past inequities shape present systems." },
  { id: "the-affordability", type: "theoretical", title: "Affordability Framework",
    method: "Redefine affordability with multidimensional data (cost, income, health).",
    output: "Theoretical framework", cost: "$",
    impact: "Establishes data-driven thought leadership." },
  { id: "the-econresilience", type: "theoretical", title: "Economic Resilience Model",
    method: "Model how efficiency investment drives local jobs and reduced costs.",
    output: "Data-backed model", cost: "$",
    impact: "Strong BD asset for local-government partnerships." },
  { id: "the-hiddencosts", type: "theoretical", title: "“Hidden Costs of Inefficiency” Model",
    method: "Model indirect costs of inefficient housing — health, productivity, maintenance.",
    output: "Conceptual model", cost: "$",
    impact: "Adds ROI depth beyond direct savings." },
  { id: "the-roiratio", type: "theoretical", title: "Cost-to-Savings Ratio Model",
    method: "Predict program ROI by intervention type, housing stock, and demographics.",
    output: "ROI model", cost: "$",
    impact: "Optimizes resource allocation." },

  /* ---------- 5. Benchmark / Dataset — new datasets for others to use ---------- */
  { id: "dat-crowdburden", type: "dataset", title: "Crowdsourced Burden Database",
    method: "Online self-report form, promoted via partner organizations.",
    output: "Open dataset", cost: "$",
    impact: "Grassroots data on real-world affordability gaps." },
  { id: "dat-barriers", type: "dataset", title: "Adoption Barriers Open Dataset",
    method: "Collect and anonymize survey data on barriers to clean-energy adoption.",
    output: "Open dataset", cost: "$",
    impact: "A shared resource for researchers and advocates." },
  { id: "dat-policy", type: "dataset", title: "Policy Comparison Database",
    method: "Compile and code local/state policies for equity-related features.",
    output: "Comparative database", cost: "$",
    impact: "A benchmark for best-practice identification." },
  { id: "dat-equitymap", type: "dataset", title: "Crowdsourced Equity Map",
    method: "Platform where residents report local issues; visualize on a live map.",
    output: "Interactive dataset + map", cost: "$",
    impact: "Real-time, community-reported advocacy data." },
  { id: "dat-archive", type: "dataset", title: "Historical Justice Archive",
    method: "Curate historical cases where policy disproportionately affected groups.",
    output: "Curated dataset", cost: "$",
    impact: "Historical context for current debates." },
  { id: "dat-residential", type: "dataset", title: "Residential Cost Dataset",
    method: "Merge public data with cleaned project insights on usage and savings.",
    output: "Cleaned dataset", cost: "$$",
    impact: "Internal asset for decisions and proposals." },
  { id: "dat-benchmark", type: "dataset", title: "Program Reduction Benchmarks",
    method: "Compare cost-saving performance across efficiency programs.",
    output: "Benchmark dataset", cost: "$",
    impact: "Evidence base for stronger proposals." },
  { id: "dat-resilience", type: "dataset", title: "Outage & Cost-Impact Dataset",
    method: "Collect outage frequency, duration, and related household costs by area.",
    output: "Resilience dataset", cost: "$",
    impact: "Reveals vulnerabilities for program design." },
  { id: "dat-appliance", type: "dataset", title: "Appliance Efficiency Benchmarks",
    method: "Gather usage patterns and ratings to rank upgrade ROI.",
    output: "Benchmark dataset", cost: "$",
    impact: "Sharpens home-audit recommendations." },

  /* ---------- 6. Survey — systematic collection of opinions or behaviors ---------- */
  { id: "sur-pulse", type: "survey", title: "Micro-Survey Pulse",
    method: "2–3 question surveys via text, events, or social, through partner channels.",
    output: "Sentiment snapshots", cost: "$",
    impact: "Quick, scalable reads on community sentiment." },
  { id: "sur-perception", type: "survey", title: "National Perception Survey",
    method: "Brief online survey on fairness perceptions across demographics.",
    output: "Sentiment-trend report", cost: "$",
    impact: "Informs advocacy strategy." },
  { id: "sur-narrative", type: "survey", title: "Narrative “My Story” Survey",
    method: "Pair structured questions with open-ended personal-story prompts.",
    output: "Mixed qual+quant dataset", cost: "$",
    impact: "Adds emotional depth to survey data." },
  { id: "sur-employer", type: "survey", title: "Employer Energy & Equity Survey",
    method: "Survey businesses on energy costs and how policy affects hiring or wages.",
    output: "Analysis report", cost: "$",
    impact: "Links energy to broader economic development." },
  { id: "sur-youth", type: "survey", title: "Youth Perspectives Survey",
    method: "School- or platform-distributed survey on how young people see the transition.",
    output: "Report", cost: "$",
    impact: "Surfaces voices missing from policy debate." },
  { id: "sur-behavior", type: "survey", title: "Behavior Survey + Analytics",
    method: "Survey habits, then model which behaviors drive savings.",
    output: "Behavior model", cost: "$$",
    impact: "Directly informs coaching programs." },
  { id: "sur-business", type: "survey", title: "Business Readiness Survey",
    method: "Survey small businesses on efficiency-adoption barriers by sector.",
    output: "Sector analysis", cost: "$",
    impact: "Identifies sectors ripe for consulting." },
  { id: "sur-satisfaction", type: "survey", title: "Post-Intervention Survey",
    method: "Survey participants after upgrades; link responses to actual usage.",
    output: "Satisfaction + effectiveness report", cost: "$",
    impact: "Measures program effectiveness." },
  { id: "sur-thermostat", type: "survey", title: "Adoption-Barriers Survey",
    method: "Identify barriers to a target technology; cluster respondents into segments.",
    output: "Segment profiles", cost: "$",
    impact: "Supports targeted marketing." },

  /* ---------- 7. Opinion — expert reflections, perspectives, manifestos ---------- */
  { id: "opi-manifesto", type: "opinion", title: "Community Co-Written Manifesto",
    method: "Facilitate a co-creation session with residents and advocates.",
    output: "Collective manifesto", cost: "$",
    impact: "Centers community voice in policy discussion." },
  { id: "opi-series", type: "opinion", title: "Manifesto Essay Series",
    method: "Co-author short manifestos with leaders, activists, and researchers.",
    output: "Open-access essay series", cost: "$",
    impact: "Amplifies diverse voices in the discourse." },
  { id: "opi-critical", type: "opinion", title: "Critical Essay",
    method: "Write a provocative piece challenging a field assumption, with case studies.",
    output: "Published essay / op-ed", cost: "$",
    impact: "Stimulates academic and public debate." },
  { id: "opi-panel", type: "opinion", title: "Panel as Research Output",
    method: "Host and record an interdisciplinary panel; edit into a publishable piece.",
    output: "Transcript essay + recording", cost: "$",
    impact: "Captures dynamic cross-field insight." },
  { id: "opi-letters", type: "opinion", title: "“Letters from the Future”",
    method: "Write fictional letters from divergent future scenarios as thought experiments.",
    output: "Speculative essays", cost: "$",
    impact: "Engages readers emotionally and intellectually." },
  { id: "opi-oped", type: "opinion", title: "Data-Driven Op-Ed",
    method: "Write an op-ed backed by internal data on real economic ripple effects.",
    output: "Op-ed", cost: "$",
    impact: "Reinforces thought-leadership positioning." },
  { id: "opi-whitepaper", type: "opinion", title: "Methods White Paper",
    method: "Showcase how data science and ML find cost-saving opportunities.",
    output: "White paper", cost: "$",
    impact: "Doubles as a corporate-marketing asset." },
  { id: "opi-annual", type: "opinion", title: "Annual State-of-the-Field Report",
    method: "Analyze yearly trends in costs, outages, and program performance.",
    output: "Annual data report", cost: "$$",
    impact: "Establishes data authority; opens contracts." },
  { id: "opi-visual", type: "opinion", title: "Visual Essay",
    method: "Tell a cost-disparity story through heat maps and infographics.",
    output: "Shareable visual essay", cost: "$",
    impact: "Highly shareable for marketing and BD." }
];
